version: '3'

services:
    nginx:
        image: nginx:1.17
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        ports:
            - 80:80
